name: Docker Build Deploy
on:
  push:
    branches: [skip ci]
  workflow_dispatch:

jobs:
  create-user-image:
  # build
  # push
  # deploy
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
