name: Docker Build Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  create-user-image:

    runs-on: [self-hosted]
    steps:
    #  code checkout 
      - name: checkout code
        uses: actions/checkout@v4.1.1

    #  reading package json for version
      - name: Read package.json
        uses: krstphrrr/package-json-version-reader@v1.0.0
        with: 
          path: "./src"
        id: package-version

    # keeping track of docker image on the hub 

      # login in to dockerhub
      - name: Docker login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # pushing image
      - name: build and push 
        id: docker_build 
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: krstphr/sami-test:${{ steps.package-version.outputs.version }}

    # deploy on remote server
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP}}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker service update sami_sami \
            --image=docker.io/krstphr/sami-test:${{ steps.package-version.outputs.version }}